# Generated by Django 5.0.4 on 2024-04-30 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=150)),
                ('CPF', models.IntegerField()),
                ('Email', models.EmailField(max_length=150)),
            ],
        ),
    ]
